### ISSUE TITLE
urllib

### ISSUE THREAD

**Issue by mhmtkcn** [johnwargo/pi_weather_station_simple#3]
hi there, thank you for sharing such great scripts john, i wanted to share few small things i found that needed updating when using latest version of RPI  5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux

for some reason import urllib2 didn't work for me

i had to change to from urllib.parse import urlencode

import urllib.parse
import urllib.request

response = urllib.request.urlopen(upload_url)

**Comment by johnwargo** [comment]
@mhmtkcn what happened? Why did you close it so fast?
